{% set version = "1.6.0" %}

package:
  name: stanza-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stanza/stanza-{{ version }}.tar.gz
  sha256: 1522178e6290a21cc02bccac9668a2b9d5cc09a5dd65c02e58dbf36bcf4295ff

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6

outputs:
  - name: stanza
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - emoji
        - numpy
        - protobuf >=3.15.0
        - python >=3.6
        - pytorch >=1.3.0
        - requests
        - six
        - tqdm
      run_constrained:
        # actual `run` dependency in stanza-with-transformers
        - transformers >=3.0.0
    test:
      imports:
        - stanza
        - stanza.models
        # check for missing `nn` members
        - stanza.models.constituency.utils
      commands:
        - pip check
      requires:
        - pip
          # test with oldest compatible version on conda-forge
        - pytorch 1.6.*

  - name: stanza-with-transformers
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("stanza", max_pin="x.x.x") }}
        - python >=3.6
        - transformers
    test:
      imports:
        - stanza
        - stanza.models
        # for transformers
        - stanza.models.common.bert_embedding
      commands:
        - pip check
        - python -c "import stanza; nl = stanza.models.constituency.utils.NONLINEARITY; print(nl); assert 'mish' in nl"
      requires:
        - pip
        # minimum with `nn.Mish`
        - pytorch >=1.9.0
    about:
      summary: (with transformers) A Python NLP Library for Many Human Languages, by the Stanford NLP Group

about:
  home: https://github.com/stanfordnlp/stanza
  summary: A Python NLP Library for Many Human Languages, by the Stanford NLP Group
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://stanfordnlp.github.io/stanza

extra:
  feedstock-name: stanza
  recipe-maintainers:
    - AngledLuffa
    - FernandezMathieu
    - bollwyvl
