{% set min_python = "python >=3.8" %}
{% set min_python = "python >=3.8" %}
{% set version = "1.8.1" %}
{% set min_python = "python >=3.8" %}

package:
  name: stanza-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stanza/stanza-{{ version }}.tar.gz
  sha256: 08c4c23e5b00a678d2d801acad85bce06e5d08d4c1af2709715647a73c4f38b7

build:
  number: 0
  noarch: python

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

outputs:
  - name: stanza
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - {{ min_python }}
      run:
        - emoji
        - networkx
        - numpy
        - protobuf >=3.15.0
        - {{ min_python }}
        - pytorch >=1.3.0
        - requests
        - six
        - toml
        - tqdm
      run_constrained:
        # actual `run` dependency in stanza-with-transformers
        - peft >=0.6.1
        - transformers >=3.0.0
    test:
      imports:
        - stanza
        - stanza.models
        # check for missing `nn` members
        - stanza.models.constituency.utils
      commands:
        - pip check
      requires:
        - pip
          # test with oldest compatible version on conda-forge
        - pytorch 1.6.*

  - name: stanza-with-transformers
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ pin_subpackage("stanza", max_pin="x.x.x") }}
        - {{ min_python }}
        - peft
        - transformers
    test:
      imports:
        - stanza
        - stanza.models
        # for transformers
        - stanza.models.common.bert_embedding
      commands:
        - pip check
        - python -c "import stanza; nl = stanza.models.constituency.utils.NONLINEARITY; print(nl); assert 'mish' in nl"
      requires:
        - pip
        # minimum with `nn.Mish`
        - pytorch >=1.9.0
    about:
      summary: (with transformers) A Python NLP Library for Many Human Languages, by the Stanford NLP Group

about:
  home: https://github.com/stanfordnlp/stanza
  summary: A Python NLP Library for Many Human Languages, by the Stanford NLP Group
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://stanfordnlp.github.io/stanza

extra:
  feedstock-name: stanza
  recipe-maintainers:
    - AngledLuffa
    - FernandezMathieu
    - bollwyvl
